update cd

diff --git a/.github/workflows/learn-github-action.yml b/.github/workflows/learn-github-action.yml
--- a/.github/workflows/learn-github-action.yml
+++ b/.github/workflows/learn-github-action.yml
@@ -20,11 +20,19 @@ jobs:
             whoami
             ls -al
             export ${{ vars.GIT_SSH_COMMAND }}
-            cd ${{vars.WORKING_DIR }} && git pull origin develop \
-            /edx/app/edxapp/venvs/edxapp/bin/i18n_tool extract  && \
-            /edx/app/edxapp/venvs/edxapp/bin/i18n_tool generate
-            cd /edx/app/edxapp/edx-platform && \
-            /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms compilejsi18n && \
-            /edx/app/edxapp/venvs/edxapp/bin/python manage.py cms compilejsi18n
-            /edx/bin/edxapp-update-assets
-            /edx/bin/supervisorctl restart lms
+            cd ${{vars.WORKING_DIR }} && git pull origin develop
+            if [ $? -eq 0 ]; then
+              cd /edx/app/edxapp/edx-platform
+              source /edx/app/edxapp/venvs/edxapp && \
+              /edx/app/edxapp/venvs/edxapp/bin/i18n_tool extract  && \
+              /edx/app/edxapp/venvs/edxapp/bin/i18n_tool generate && \
+              /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms compilejsi18n && \
+              /edx/app/edxapp/venvs/edxapp/bin/python manage.py cms compilejsi18n
+              if [ $? -eq 0 ]; then
+                /edx/bin/edxapp-update-assets
+                /edx/bin/supervisorctl restart lms
+              else
+                echo "Compile i18n failed" && exit 1
+            else
+              echo "Pull code failed" && exit 1
+            fi
