update workflow

diff --git a/.github/workflows/sync-specific-folder.yml b/.github/workflows/sync-specific-folder.yml
--- a/.github/workflows/sync-specific-folder.yml
+++ b/.github/workflows/sync-specific-folder.yml
@@ -28,14 +28,13 @@ jobs:
               echo "Start sync branch: $element"
               git checkout "$element"
               git fetch origin
-              git cherry-pick -m 1 "$commit_hash" 
-              # >/dev/null 2>&1
+              git cherry-pick -m 1 "$commit_hash" >> /dev/null 2>&1
               # # Check if cherry-pick was successful
-              # if [ $? -eq 0 ]; then
-              #     git push origin "$element"
-              #     echo "Success sync branch $element!"
-              # else
-              #     git cherry-pick --abort
-              #     echo "Failed sync branch $element!"
-              # fi
+              if [ $? -eq 0 ]; then
+                  git push origin "$element"
+                  echo "Success sync branch $element!"
+              else
+                  git cherry-pick --abort
+                  echo "Failed sync branch $element!"
+              fi
           done
