update config

diff --git a/.github/workflows/sync-specific-folder.yml b/.github/workflows/sync-specific-folder.yml
--- a/.github/workflows/sync-specific-folder.yml
+++ b/.github/workflows/sync-specific-folder.yml
@@ -54,39 +54,48 @@ jobs:
       #             echo "\e[31mCherry pick failed on $branch\e[0m"
       #           fi
       #       done
-      - name: Configure SSH
-        run: |
-            sudo apt update && sudo apt install openssh-server && sudo systemctl start ssh
-            mkdir -p ~/.ssh/
-            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
-            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
-      - name: Pull code in production environment
-        run: |
-          ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_HOST }} && pwd
-          whoami
-          # IFS="," read -r -a theme_folders <<< ${{ vars.SITE_BRANCHES }}
-          # # IFS="," read -r -a branches <<< ${{ vars.SITE_BRANCHES }}
-          # # Loop through each branch and pull the latest code
-          # for theme in "${theme_folders[@]}"
-          # do
-          #   echo "checkout & pull '$theme'"
-          #   sudo -u edxapp bash -c 'cd ${{vars.WORKING_DIR }}/$theme && git pull'
-          #   git checkout "${branches[i]}"
-          #   if [ $? -eq 0 ]; then
-          #     git restore .
-          #     git pull origin "${branches[i]}"
-          #     if [ $? -eq 0 ]; then
-          #       echo "Successfully pulled latest code for branch '${branches[i]}'. \n"
-          #       cd ..
-          #     else
-          #       echo "Failed to pull code for branch '${branches[i]}'."
-          #       exit 0
-          #     fi
-          #   else
-          #     echo "Failed to checkout branch '${branches[i]}'."
-          #     exit 0
-          #   fi
-          # done
-          echo "Successfully pulled all branch in ${branches}"
+      - name: Pull code
+        uses: appleboy/ssh-action@v1.0.0
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.SSH_KEY }}
+          script: |
+              whoami
+              pwd
+      # - name: Configure SSH
+      #   run: |
+      #       sudo apt update && sudo apt install openssh-server && sudo systemctl start ssh
+      #       mkdir -p ~/.ssh/
+      #       echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
+      #       chmod 600 ~/.ssh/id_rsa
+      #       ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
+      # - name: Pull code in production environment
+      #   run: |
+      #     ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_HOST }} && pwd
+      #     whoami
+      #     # IFS="," read -r -a theme_folders <<< ${{ vars.SITE_BRANCHES }}
+      #     # # IFS="," read -r -a branches <<< ${{ vars.SITE_BRANCHES }}
+      #     # # Loop through each branch and pull the latest code
+      #     # for theme in "${theme_folders[@]}"
+      #     # do
+      #     #   echo "checkout & pull '$theme'"
+      #     #   sudo -u edxapp bash -c 'cd ${{vars.WORKING_DIR }}/$theme && git pull'
+      #     #   git checkout "${branches[i]}"
+      #     #   if [ $? -eq 0 ]; then
+      #     #     git restore .
+      #     #     git pull origin "${branches[i]}"
+      #     #     if [ $? -eq 0 ]; then
+      #     #       echo "Successfully pulled latest code for branch '${branches[i]}'. \n"
+      #     #       cd ..
+      #     #     else
+      #     #       echo "Failed to pull code for branch '${branches[i]}'."
+      #     #       exit 0
+      #     #     fi
+      #     #   else
+      #     #     echo "Failed to checkout branch '${branches[i]}'."
+      #     #     exit 0
+      #     #   fi
+      #     # done
+      #     echo "Successfully pulled all branch in ${branches}"
 
