update config

diff --git a/.github/workflows/sync-specific-folder.yml b/.github/workflows/sync-specific-folder.yml
--- a/.github/workflows/sync-specific-folder.yml
+++ b/.github/workflows/sync-specific-folder.yml
@@ -1,40 +1,36 @@
 name: sync-specific-folder
 run-name: ${{ github.actor }} is running sync folder
 on:
-  # push:
-    # branches:
-    #   - pr-branch
-    # paths:
-    #   - templates/**
   pull_request_target:
     branches:
       - main
     types:
       - closed
 
-    # paths:
-    #   - templates/**
 jobs:
   sync-branch:
     if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'sync-branch')
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: sync branch
+    - name: sync site branch with change of merge commit
       run: |
-          echo ${{ github.event.pull_request.labels[0].name }}
-          # gh api -H "Accept: application/vnd.github+json" /repos/namnv176-dev/ci-cd-sample/issues/${{ github.event.pull_request.number }}/labels | jq '[.[].name]' > /tmp/label_list
-          # cat /tmp/label_list
-          # elements = ${{github.event.pull_request.labels.*.name}}
-          # for element in "${elements[@]}"
-          # do
-          #     echo "$element"
-          # done
-          # echo ${{github.event.pull_request.labels.*.name}}
-          # git checkout sync-branch
-          # git checkout -- templates # Reset the templates folder to the state of the 'theme' branch
-          # git checkout main
-          # git checkout -- templates # Update the templates folder from the 'theme' branch
-          # git add templates
-          # git commit -m "Update templates folder in theme1 branch"
-          # git push origin sync-branch
+          commit_hash=${{github.event.pull_request.sha}}
+          git fetch origin
+          IFS="," read -r -a branches <<< "${{ vars.SITE_BRANCHES }}"
+
+          # Loop through the array elements
+          for element in "${branches[@]}"
+          do
+              echo "Start sync branch: $element"
+              git checkout "$element"
+              git cherry-pick "$commit_hash" >/dev/null 2>&1
+              # Check if cherry-pick was successful
+              if [ $? -eq 0 ]; then
+                  git push origin "$element"
+                  echo "Success sync branch $element!"
+              else
+                  git cherry-pick --abort
+                  echo "Failed sync branch $element!"
+              fi
+          done
