update workflow

diff --git a/.github/workflows/sync-specific-folder.yml b/.github/workflows/sync-specific-folder.yml
--- a/.github/workflows/sync-specific-folder.yml
+++ b/.github/workflows/sync-specific-folder.yml
@@ -14,27 +14,28 @@ jobs:
     environment:
       name: production
     steps:
-    - uses: actions/checkout@v2
-    - name: sync site branch with change of merge commit
-      run: |
-          git fetch origin
-          git branch
-          commit_hash=${{ github.event.pull_request.base.sha }}
-          IFS="," read -r -a branches <<< ${{ vars.SITE_BRANCHES }}
+      - name: Checkout node
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: sync site branch with change of merge commit
+        run: |
+            git branch
+            commit_hash=${{ github.event.pull_request.base.sha }}
+            IFS="," read -r -a branches <<< ${{ vars.SITE_BRANCHES }}
 
-          # Loop through the array elements
-          for element in "${branches[@]}"
-          do
-              echo "Start sync branch: $element"
-              git checkout "$element"
-              git fetch origin
-              git cherry-pick -m 1 "$commit_hash" >> /dev/null 2>&1
-              # # Check if cherry-pick was successful
-              if [ $? -eq 0 ]; then
-                  git push origin "$element"
-                  echo "Success sync branch $element!"
-              else
-                  git cherry-pick --abort
-                  echo "Failed sync branch $element!"
-              fi
-          done
+            # Loop through the array elements
+            for element in "${branches[@]}"
+            do
+                echo "Start sync branch: $element"
+                git checkout "$element"
+                git cherry-pick -m 1 "$commit_hash" > /dev/null 2>&1
+                # # Check if cherry-pick was successful
+                if [ $? -eq 0 ]; then
+                    git push origin "$element"
+                    echo "Success sync branch $element!"
+                else
+                    git cherry-pick --abort
+                    echo "Failed sync branch $element!"
+                fi
+            done
